SELECT B.ITEM_ID, 
       (SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_ID=B.ITEM_ID) AS ITEM_NAME, 
       (SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID=B.ITEM_ID) AS RARITY
FROM ITEM_INFO A, ITEM_TREE B
WHERE A.ITEM_ID = B.PARENT_ITEM_ID 
  AND A.RARITY='RARE'
ORDER BY B.ITEM_ID DESC;
  
